# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'Knit' do
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'RKDropdownAlert'
    pod 'UIFloatLabelTextField'
	pod 'YLGIFImage'
    pod 'PulsingHalo'
    pod 'Google/SignIn'
end


